<?php 
return [
 'config_meta_tag_keywords' => 'asd'  ,
 'config_fb_url' => 'https://www.facebook.com/'  ,
 'config_linkedin_url' => 'https://www.linkedin.com/'  ,
 'config_twitter_url' => 'https://twitter.com/login?lang=en'  ,
 'config_youtube_url' => 'https://www.youtube.com/channel/UCiWzLziMAOk-oB0pig8TkEg/'  ,
 'config_mail_engine' => 'smtp'  ,
 'config_insta_url' => 'https://www.instagram.com/'  ,
 'config_smtp_username' => 'srinivasaraouesi@gmail.com'  ,
 'config_smtp_hostname' => 'smtp.gmail.com'  ,
 'config_smtp_password' => 'adawzvdkqkukvfyy'  ,
 'config_smtp_timeout' => '250'  ,
 'config_smtp_port' => '587'  ,
 'config_store_image' => '1695681082WhatsApp Image 2023-09-15 at 12.12.57 PM (2).jpeg'  ,
 'config_alert_mail' => 'Register,Orders'  ,
 'config_icon_image' => '1695681092WhatsApp Image 2023-09-15 at 12.12.57 PM (2).jpeg'  ,
 'config_currency' => '₹'  ,
 'config_fax' => '380001'  ,
 'config_telephone' => '09898989898'  ,
 'config_email' => 'otrixapp@gmail.in'  ,
 'config_geocode' => '54654'  ,
 'config_store_owner' => 'UESI-TS Admin'  ,
 'config_address' => 'Building Number 121
Ground floor, Office 2 Otrixweb
Commercial, Otrixcity'  ,
 'config_store_name' => 'UESI-TS  update'  ,
 'config_meta_tag_description' => 'asd'  ,
 'config_meta_title' => 'sad'  ,
 'config_web_bg' => '#F24C62'  ,
 'config_currency' => '₹'  ,
 'config_fax' => '380001'  ,
 'config_telephone' => '09898989898'  ,
 'config_email' => 'otrixapp@gmail.in'  ,
 'config_geocode' => '54654'  ,
 'config_address' => 'Building Number 121
Ground floor, Office 2 Otrixweb
Commercial, Otrixcity'  ,
 'config_store_owner' => 'UESI-TS Admin'  ,
 'config_store_name' => 'UESI-TS  update'  ,
 'config_encryption' => ''  ,
 'config_from' => 'srinivasaraouesi@gmail.com'  ,
 'config_from_name' => 'UESI TS Mobile App'  ,
 'config_signup_discount_status' => '1'  ,
 'config_signup_discount' => '15'  ,
 'config_signup_discount_text' => 'Sign Up  And  _DISCOUNT_  special discount on your first order'  ,
 'config_layout' => 'otrixlayout'  ,
];
